apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJTR1ZuWlhNNloyaHdYMk5aT1RWWFFtOUhiRFY0UnpWcFZEVkxUekZ4ZERRMFpuaEdUMVV6YmpRd1NVSjBPQT09In19fQ==
type: kubernetes.io/dockerconfigjson
